proxy="--proxy socks5://127.0.0.1:1080/"
proxy=""
postfix="-%(playlist_index)02d.%(ext)s"
format="-f 18"
format="-f 18 --extract-audio --audio-format mp3"
args="-k --verbose"
args="-k -i"

gzx="春江花月夜"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjEhTsblX3yN7n4Q9E0x-qpf"
gzx="孟丽君"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjFVgbug69O7lvpSZijWeN4h"
gzx="杨家将"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjFyn_WPmCzorc9r8RWCWkwf"
gzx="薛丁山救五美"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjFuQamJ2teKg2lA7hokX8ph"
gzx="描金扇"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjGvi2WdCiX8WMYGoVPEfa4e"
gzx="红尘客"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjGMY3TTHyywa-mzzwB4JM6Y"
gzx="新七侠五义"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjGCM7SnsPeShfgk6iqrJDnW"
gzx="赵匡胤"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjFFi6VaNY83OiTMkDc3wv7B"
gzx="陈三五娘"
url="https://www.youtube.com/watch?list=PL2FfYhEj_1e4Ansz4C6LELXG5FBruD9Oh"
gzx="薛平贵与王宝钏"
url="https://www.youtube.com/watch?list=PL8MwjIpV5cFV6QwRN5pB2bTDeE8_q-8aQ"

gzx="人面桃花"
url="https://www.youtube.com/watch?list=PLWF0QXWmbnjHA7Q5JYWAONO0DJkm5m-vK"
gzx="玉楼春"
url="https://www.youtube.com/watch?list=PL8MwjIpV5cFUJcvEld540FKIVRCeMquMo"
gzx="秦淮烟雨"
url="https://www.youtube.com/watch?list=PL9v187Z2l2r3VfFzduhvb_Ouy3Hj1ZQSF"
mkdir $gzx ; cd $gzx && (youtube-dl $args $proxy $format -o "$gzx$postfix" $url || cd .) && cd -
